name: Continuous Integration

on:
  push:
    branches: development
  pull_request:
    branches: development

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies with Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          poetry install

      - name: Run tests with Poetry
        run: poetry run pytest

      - name: Build Docker image
        run: docker build -t my_app:latest .

      - name: Run Docker container
        run: docker run --rm my_app:latest
